### ISSUE TITLE
Jira Acror failes when no Actie Sprint found

### ISSUE THREAD

**Issue by SergeyDz** [SergeyDz/SlackToJiraBot#6]
[ERROR] [08/29/2016 10:59:38.915] [bot-system-akka.actor.default-dispatcher-44] [akka://bot-system/user/SlackEventListener-plumbers-sdzyuban/$c] null
java.lang.NullPointerException
	at sd.samples.akka.slacktojirabot.Mapping.Message.JiraIssuesResultFormatter.getUserPic(JiraIssuesResultFormatter.java:151)
	at sd.samples.akka.slacktojirabot.Mapping.Message.JiraChangelogFormatter.convertChangelogFields(JiraChangelogFormatter.java:60)
	at sd.samples.akka.slacktojirabot.Mapping.Message.JiraChangelogFormatter.lambda$call$0(JiraChangelogFormatter.java:35)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at sd.samples.akka.slacktojirabot.Mapping.Message.JiraChangelogFormatter.call(JiraChangelogFormatter.java:33)
	at sd.samples.akka.slacktojirabot.Mapping.Attachment.JiraIssuesToAttachmentFormatter.lambda$call$0(JiraIssuesToAttachmentFormatter.java:53)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at sd.samples.akka.slacktojirabot.Mapping.Attachment.JiraIssuesToAttachmentFormatter.call(JiraIssuesToAttachmentFormatter.java:40)
	at sd.samples.akka.slacktojirabot.Jira.JiraFilterActor.onReceive(JiraFilterActor.java:106)
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:167)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
	at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:97)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by SergeyDz** [comment]
Fixed, resolved
